# CMake generated Testfile for 
# Source directory: /Users/link/dev/PixelUI/tests
# Build directory: /Users/link/dev/PixelUI/build-asan/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(application_stack_test "/Users/link/dev/PixelUI/build-asan/tests/application_stack_test")
set_tests_properties(application_stack_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;4;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(view_manager_lifecycle_test "/Users/link/dev/PixelUI/build-asan/tests/view_manager_lifecycle_test")
set_tests_properties(view_manager_lifecycle_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;13;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(chart_buffer_test "/Users/link/dev/PixelUI/build-asan/tests/chart_buffer_test")
set_tests_properties(chart_buffer_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;22;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(value_binding_test "/Users/link/dev/PixelUI/build-asan/tests/value_binding_test")
set_tests_properties(value_binding_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;27;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(numeric_components_test "/Users/link/dev/PixelUI/build-asan/tests/numeric_components_test")
set_tests_properties(numeric_components_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;32;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(animation_inline_test "/Users/link/dev/PixelUI/build-asan/tests/animation_inline_test")
set_tests_properties(animation_inline_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;41;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(popup_base_lifecycle_test "/Users/link/dev/PixelUI/build-asan/tests/popup_base_lifecycle_test")
set_tests_properties(popup_base_lifecycle_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;50;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(popup_pool_test "/Users/link/dev/PixelUI/build-asan/tests/popup_pool_test")
set_tests_properties(popup_pool_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;59;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(popup_value_digits_test "/Users/link/dev/PixelUI/build-asan/tests/popup_value_digits_test")
set_tests_properties(popup_value_digits_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;68;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(popup_progress_test "/Users/link/dev/PixelUI/build-asan/tests/popup_progress_test")
set_tests_properties(popup_progress_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;77;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(num_scroll_test "/Users/link/dev/PixelUI/build-asan/tests/num_scroll_test")
set_tests_properties(num_scroll_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;86;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(icon_view_layout_test "/Users/link/dev/PixelUI/build-asan/tests/icon_view_layout_test")
set_tests_properties(icon_view_layout_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;95;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(focus_manager_transition_test "/Users/link/dev/PixelUI/build-asan/tests/focus_manager_transition_test")
set_tests_properties(focus_manager_transition_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;104;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(widget_tree_test "/Users/link/dev/PixelUI/build-asan/tests/widget_tree_test")
set_tests_properties(widget_tree_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;113;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(label_font_test "/Users/link/dev/PixelUI/build-asan/tests/label_font_test")
set_tests_properties(label_font_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;122;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(render_scheduling_test "/Users/link/dev/PixelUI/build-asan/tests/render_scheduling_test")
set_tests_properties(render_scheduling_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;131;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(blink_state_test "/Users/link/dev/PixelUI/build-asan/tests/blink_state_test")
set_tests_properties(blink_state_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;140;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(canvas_camera_test "/Users/link/dev/PixelUI/build-asan/tests/canvas_camera_test")
set_tests_properties(canvas_camera_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;149;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
add_test(list_view_camera_test "/Users/link/dev/PixelUI/build-asan/tests/list_view_camera_test")
set_tests_properties(list_view_camera_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/link/dev/PixelUI/tests/CMakeLists.txt;158;add_test;/Users/link/dev/PixelUI/tests/CMakeLists.txt;0;")
